config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :articles do
      resources :comments
    end
  end

  root 'blogs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_many :blogs
end

app/controllers/application_controller.rb
# Super class for all other controllers
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :description])
  end
end

app/controllers/articles_controller.rb
# Controller for articles in blogs
class ArticlesController < ApplicationController
  def index
    @blog = Blog.find(params[:blog_id])
    @articles = @blog.articles.all
  end

  def show
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:id])
  end

  def new
    @blog = Blog.find(params[:blog_id])
    @article = @blog.articles.build
  end

  def edit
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:id])
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @article = @blog.articles.build(article_params)

    if @article.save
      redirect_to blog_article_path(@blog, @article)
    else
      render 'new'
    end
  end

  def update
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to blog_article_path(@blog, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:id])
    @article.destroy!

    redirect_to blog_articles_path(@blog)
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/blogs_controller.rb
# Controller for blogs
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to @blog
    else
      render 'edit'
    end
  end

  def destroy
    # There's a series of callbacks associated with destroy. If the before_destroy
    #   callback throws :abort the action is cancelled and destroy returns false.
    # There's a series of callbacks associated with destroy!. If the before_destroy
    #   callback throws :abort the action is cancelled and destroy! raises ActiveRecord::RecordNotDestroyed.
    @blog = Blog.find(params[:id])
    @blog.destroy!

    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:name)
  end
end

app/controllers/comments_controller.rb
# Controller for comments of articles
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to blog_article_path(@blog, @article)
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_article_path(@blog, @article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.slim
/ without explicitly declared error messages no error messages raised - probably because of simple_form
= simple_form_for ([@blog, @blog.articles.build]) do |f|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved: 
      ul
        - @article.errors.full_messages.each do |msg|
          li
            = msg
  = f.input :title
  = f.input :text
  p
  = f.button :submit
end

app/views/articles/edit.html.slim
h1
  | Editing article
= simple_form_for :article, url: blog_article_path(@blog), method: :patch do |f|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved: 
      ul
        - @article.errors.full_messages.each do |msg|
          li
            = msg
  = f.input :title
  = f.input :text, :as => :text
  p
  = f.button :submit
= link_to 'Back', blog_articles_path(@blog)

app/views/articles/index.html.slim
h1
  | Listing Articles
= link_to 'Create new Article', new_blog_article_path(@blog)
table.table
  tr
    th
      | Title
    th
      | Text
    th[colspan="3"]
  - @articles.each do |article|
    tr
      td
        = article.title
      td
        = article.text
      td
        = link_to 'Show', blog_article_path(@blog, article)
      td
        = link_to 'Edit', edit_blog_article_path(@blog, article)
      td
        = link_to 'Destroy', blog_article_path(@blog, article), method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'Back',blogs_path

app/views/articles/new.html.slim
h1
  | New article
= render 'form'
= link_to 'Back', blog_articles_path(@blog)

app/views/articles/show.html.slim
h1
  | Article:
p
  strong
    | Title:
  = @article.title
p
  strong
    | Text:
  = @article.text
h2
  | Comments
= render @article.comments
h2
  | Add a comment:
= simple_form_for([@blog, @article, @article.comments.build]) do |f|
  = f.input :commenter
  = f.input :body
  = f.button :submit
= link_to 'Edit', edit_blog_article_path(@blog, @article)
|  | 
= link_to 'Back', blog_articles_path(@blog)

app/views/blogs/_form.html.slim
= simple_form_for @blog do |f|
    = f.input :name
    = f.button :submit
end

app/views/blogs/edit.html.slim
h1
  | Edit Blog
= render 'form'
= link_to 'Back', blogs_path

app/views/blogs/index.html.slim
h1
  | Listing Blogs
= link_to 'New Blog', new_blog_path, {:class => "btn btn-primary", :role => "button"}
table.table
  tr
    th
      | Title
  - @blogs.each do |blog|
    tr
      td
        = blog.name
      td
        = link_to 'Show', blog_articles_path(blog)
      td
        = link_to 'Edit', edit_blog_path(blog)
      td
        = link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' }

app/views/blogs/new.html.slim
h1
  | New Blog
= render 'form'
= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
h1
  | Blog: 
p
  strong
    | Name:
  = @blog.name
= link_to 'Show Articles',blog_articles_path(@blog)
|  |
= link_to 'Back',blogs_path

app/views/comments/_comment.html.slim
p
  strong
    | Commenter:
  = comment.commenter
p
  strong
    | Comment:
  = comment.body
= link_to 'Destroy Comment', [@blog, @article, comment], method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      p.notice
        = notice
      p.alert
        = alert
    .container
      ul.nav
        li.nav-item
          = link_to 'Root', root_path, { :class=>"nav-link" }
        li.nav-item
          = link_to 'Profile', edit_user_registration_path, { :class=>"nav-link" }
        li.nav-item
          = link_to 'Logout', destroy_user_session_path, {:name => "delB", :class=>"nav-link", :method => :delete,data: { confirm: 'Are you sure?' } }
      = yield